/**
 * ThesisHCMUS Gateway API client.
 *
 * The VieTrans UI is kept intact, but the network contract is adapted to the
 * current async Node.js Gateway:
 * POST /api/image-translations/jobs -> poll /jobs/:jobId -> render /result.
 */

const API_BASE = import.meta.env.VITE_API_URL || 'http://localhost:3000';

const IMAGE_TRANSLATION_BASE = `${API_BASE}/api/image-translations`;

// ─── Types ──────────────────────────────────────────────────────────────────

export type GatewayJobStatus = 'queued' | 'processing' | 'completed' | 'failed';

export interface GatewayJob {
  jobId: string;
  status: GatewayJobStatus;
  originalName: string;
  inputFile: string;
  outputFile: string;
  resultUrl: string;
  error: string | null;
  createdAt: string;
  updatedAt: string;
  completedAt?: string | null;
}

export interface PipelineStages {
  input: string;
  back: string;
  text_en: string;
  text_vi: string;
  fuse: string;
}

export interface SampleDetail {
  id: number | string;
  tit: string;
  ocr: string;
  stages: PipelineStages;
}

export interface SampleListItem {
  id: number | string;
  tit: string;
  ocr: string;
}

export interface SamplesPage {
  page: number;
  limit: number;
  total: number;
  total_pages: number;
  samples: SampleListItem[];
}

export interface UploadResult {
  matched_id: number | string;
  match_quality: 'good' | 'approximate' | 'random' | 'live_inference';
  hamming_distance: number;
  tit: string;
  ocr: string;
  stages: PipelineStages;
  job: GatewayJob;
}

export interface PipelineInfo {
  total_samples: number;
  stages: { key: string; name: string; name_en: string }[];
  models: Record<string, Record<string, unknown>>;
  image_size: { width: number; height: number };
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

function delay(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function parseJson<T>(response: Response): Promise<T> {
  const body = await response.json().catch(() => ({}));

  if (!response.ok) {
    const message =
      typeof body === 'object' && body && 'message' in body
        ? String((body as { message?: unknown }).message)
        : 'Request failed';
    throw new Error(message);
  }

  return body as T;
}

function buildResultUrl(job: GatewayJob): string {
  return `${job.resultUrl}?v=${encodeURIComponent(job.updatedAt || '')}`;
}

function mapJobToUploadResult(job: GatewayJob): UploadResult {
  return {
    matched_id: job.jobId,
    match_quality: 'live_inference',
    hamming_distance: 0,
    tit: job.originalName || `Job ${job.jobId.slice(0, 8)}`,
    ocr: job.status === 'completed'
      ? 'Result image generated by the asynchronous worker pipeline.'
      : job.error || `Current job state: ${job.status}`,
    stages: {
      input: '',
      back: '',
      text_en: '',
      text_vi: '',
      fuse: buildResultUrl(job),
    },
    job,
  };
}

// ─── API Functions ──────────────────────────────────────────────────────────

export async function checkHealth(): Promise<{ status: string; total_samples: number }> {
  const response = await fetch(`${API_BASE}/api/health`);
  const body = await parseJson<{ ok: boolean; service: string }>(response);

  return {
    status: body.ok ? 'ok' : 'error',
    total_samples: 0,
  };
}

export async function getPipelineInfo(): Promise<PipelineInfo> {
  return {
    total_samples: 0,
    image_size: { width: 0, height: 0 },
    stages: [
      { key: 'upload', name: 'Upload', name_en: 'Upload' },
      { key: 'queue', name: 'Queue', name_en: 'Queue' },
      { key: 'worker', name: 'Worker', name_en: 'Worker' },
      { key: 'result', name: 'Result', name_en: 'Result' },
    ],
    models: {
      gateway: { stack: 'Node.js / Express / Mongoose' },
      queue: { stack: 'RabbitMQ' },
      worker: { stack: 'Python / FastAPI' },
    },
  };
}

export async function listSamples(page = 1, limit = 20): Promise<SamplesPage> {
  return {
    page,
    limit,
    total: 0,
    total_pages: 0,
    samples: [],
  };
}

export async function getSample(id: number | string): Promise<SampleDetail> {
  throw new Error(`Sample ${id} is not available in the current gateway API.`);
}

export async function getRandomSample(): Promise<SampleDetail> {
  throw new Error('Random samples are not available in the current gateway API.');
}

export async function createImageTranslationJob(file: File): Promise<GatewayJob> {
  const formData = new FormData();
  formData.append('image', file);

  const response = await fetch(`${IMAGE_TRANSLATION_BASE}/jobs`, {
    method: 'POST',
    body: formData,
  });

  return parseJson<GatewayJob>(response);
}

export async function getImageTranslationJob(jobId: string): Promise<GatewayJob> {
  const response = await fetch(`${IMAGE_TRANSLATION_BASE}/jobs/${jobId}`);
  return parseJson<GatewayJob>(response);
}

export async function waitForImageTranslationJob(jobId: string): Promise<GatewayJob> {
  const maxAttempts = 120;

  for (let attempt = 0; attempt < maxAttempts; attempt += 1) {
    const job = await getImageTranslationJob(jobId);

    if (job.status === 'completed') {
      return job;
    }

    if (job.status === 'failed') {
      throw new Error(job.error || 'Image translation failed.');
    }

    await delay(1000);
  }

  throw new Error('Image translation timed out.');
}

export async function uploadImage(file: File): Promise<UploadResult> {
  const createdJob = await createImageTranslationJob(file);
  const completedJob = await waitForImageTranslationJob(createdJob.jobId);
  return mapJobToUploadResult(completedJob);
}

/** Build full image URL from API path */
export function imageUrl(apiPath: string): string {
  if (!apiPath) {
    return '';
  }

  if (
    apiPath.startsWith('http://') ||
    apiPath.startsWith('https://') ||
    apiPath.startsWith('blob:') ||
    apiPath.startsWith('data:')
  ) {
    return apiPath;
  }

  return `${API_BASE}${apiPath}`;
}

/** Build thumbnail URL */
export function thumbUrl(stage: string, id: number | string): string {
  return `${IMAGE_TRANSLATION_BASE}/jobs/${id}/result?stage=${encodeURIComponent(stage)}`;
}
